name: Issue Open Checkbox

on:
  issues:
    types: [opened, reopened]

jobs:
  check-checkbox:
    runs-on: ubuntu-latest
    permissions: 
      issues: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Close issue on check
      if: contains(github.event.issue.body, '- [X] I didn''t check all the checkboxes')
      uses: actions-cool/issues-helper@v3
      with:
        actions: 'create-comment,add-labels,close-issue'
        labels: 'invalid'
        body: |
          The issue is closed because it should be. If you want to re-open it, please edit and check your issue then re-open it.
          这个议题因为应被关闭而被关闭了。如果你想要重新打开它，请编辑并检查你的议题再重新打开它。

    - name: Comment issue on not check
      if: contains(github.event.issue.body, '- [ ] I didn''t check all the checkboxes')
      uses: actions-cool/issues-helper@v3
      with:
        actions: 'create-comment,remove-labels,add-assignees'
        labels: 'invalid'
        assignees: 'lingfengyu-dreaming'
        body: |
          Thank you for confirming the issue.
          感谢提交议题。

    - name: Comment issue on no checkbox
      if: contains(github.event.issue.body, '- [ ] I didn''t check all the checkboxes') == false && contains(github.event.issue.body, '- [X] I didn''t check all the checkboxes') == false
      uses: actions-cool/issues-helper@v3
      with:
        actions: 'create-comment,add-labels,add-assignees'
        labels: 'not template,help wanted'
        assignees: 'lingfengyu-dreaming'
        body: |
          Your issue is not generated from template. Please make sure your issue includes all the necessary infomation. If not, your issue may be close immediately. If you submitted this issue from template, please ignore this message, there may be some problems.
          你的议题不是从模板生成的。请确保你的议题包含所有必须的信息。如果没有，你的议题可能会立刻被关闭。如果你从模板新建了这个议题，请忽略这条消息，可能出现了一些问题。